metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: couchbase
  period: 10s
  hosts: ["172.17.0.1:8091"]
  username: "Administrator"
  password: "password"
  enabled: true

- module: elasticsearch
  period: 10s
  hosts: ["http://172.17.0.1:9200"]

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
  - add_cloud_metadata: ~

setup.kibana:
  host: "172.17.0.1:5601"

output.elasticsearch:
  hosts: '172.17.0.1:9200'  
